### ISSUE TITLE
Omission of 2 VeriSign CA certs?

### ISSUE THREAD

**Issue by adc-dajones** [certifi/python-certifi#28]
If this is not the right forum for this question please suggest the correct one.

Certifi owners,

After upgrading python requests module from v2.3.0 to v2.4.0 SSL cert verification against one of our API webservers began to fail. We see that v2.4 requires certifi to provide the cacert.pem. We confirmed that our request.get() call is using this new certifi cacert.pem. The error we're seeing is:
```
requests.exceptions.SSLError: [Errno 1] _ssl.c:490: error:14090086:SSL routines:SSL3_GET_SERVER_CERTIFICATE:certificate verify failed
```

After some digging we found that you have removed the VeriSign CA certs that our target cert requires for verification. The CA certs in question exist both in the requests module's cacert.pem (now unused) and redhat OS' default ca-bundle.crt. Locations for your reference:
* certifi: /usr/lib/python2.6/site-packages/certifi/cacert.pem
* requests: /usr/lib/python2.6/site-packages/requests/cacert.pem
* redhat: /etc/pki/tls/certs/ca-bundle.crt

Versions in use:
* certifi==2015.9.6.2
* requests==2.4.0
* Python 2.6.6
* Red Hat Enterprise Linux Server release 6.4 (Santiago)
* OpenSSL 0.9.8zc-fips 15 Oct 2014

**Question 1: was the omission of these two certs (provided below) an oversight or was there a good reason they were removed?**

**Question 2: If an oversight when can we expect them to be added back in?**

CA bundle existence: requests module yes, redhat yes, certifi no.
C:US, O:VeriSign, Inc., OU: Class 3 Public Primary Certification Authority
serial_num: 149843929435818692848040365716851702463
```
-----BEGIN CERTIFICATE-----
MIICPDCCAaUCEHC65B0Q2Sk0tjjKewPMur8wDQYJKoZIhvcNAQECBQAwXzELMAkG
A1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFz
cyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTk2
MDEyOTAwMDAwMFoXDTI4MDgwMTIzNTk1OVowXzELMAkGA1UEBhMCVVMxFzAVBgNV
BAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFzcyAzIFB1YmxpYyBQcmlt
YXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQDJXFme8huKARS0EN8EQNvjV69qRUCPhAwL0TPZ2RHP7gJYHyX3KqhE
BarsAx94f56TuZoAqiN91qyFomNFx3InzPRMxnVx0jnvT0Lwdd8KkMaOIG+YD/is
I19wKTakyYbnsZogy1Olhec9vn2a/iRFM9x2Fe0PonFkTGUugWhFpwIDAQABMA0G
CSqGSIb3DQEBAgUAA4GBALtMEivPLCYATxQT3ab7/AoRhIzzKBxnki98tsX63/Do
lbwdj2wsqFHMc9ikwFPwTtYmwHYBV4GSXiHx0bH/59AhWM1pF+NEHJwZRDmJXNyc
AA9WjQKZ7aKQRUzkuxCkPfAyAw7xzvjoyVGM5mKf5p/AfbdynMk2OmufTqj/ZA1k
-----END CERTIFICATE-----
```

CA bundle existence: requests module yes, redhat no, certifi no.
C:US, O:VeriSign, Inc., OU:Class 3 Public Primary Certification Authority
serial_num: 80507572722862485515306429940691309246
```
-----BEGIN CERTIFICATE-----
MIICPDCCAaUCEDyRMcsf9tAbDpq40ES/Er4wDQYJKoZIhvcNAQEFBQAwXzELMAkG
A1UEBhMCVVMxFzAVBgNVBAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFz
cyAzIFB1YmxpYyBQcmltYXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MB4XDTk2
MDEyOTAwMDAwMFoXDTI4MDgwMjIzNTk1OVowXzELMAkGA1UEBhMCVVMxFzAVBgNV
BAoTDlZlcmlTaWduLCBJbmMuMTcwNQYDVQQLEy5DbGFzcyAzIFB1YmxpYyBQcmlt
YXJ5IENlcnRpZmljYXRpb24gQXV0aG9yaXR5MIGfMA0GCSqGSIb3DQEBAQUAA4GN
ADCBiQKBgQDJXFme8huKARS0EN8EQNvjV69qRUCPhAwL0TPZ2RHP7gJYHyX3KqhE
BarsAx94f56TuZoAqiN91qyFomNFx3InzPRMxnVx0jnvT0Lwdd8KkMaOIG+YD/is
I19wKTakyYbnsZogy1Olhec9vn2a/iRFM9x2Fe0PonFkTGUugWhFpwIDAQABMA0G
CSqGSIb3DQEBBQUAA4GBABByUqkFFBkyCEHwxWsKzH4PIRnN5GfcX6kb5sroc50i
2JhucwNhkcV8sEVAbkSdjbCxlnRhLQ2pRdKkkirWmnWXbj9T/UWZYB2oK0z5XqcJ
2HUw19JlYD1n1khVdWk/kfVIC0dpImmClr7JyDiGSnoscxlIaU5rfGW/D/xwzoiQ
-----END CERTIFICATE-----
```

Thank you for your time. Let me know if I can help.

This is a re-post of https://github.com/certifi/certifi.io/issues/10 as suggested by sigmavirus24 

Sorry for my ignorance but...

Question #3: I believe the above root certs are 1024-bit. Is that the issue?

Question #4: how does openSSL determine which root cert to use for verification?

**Comment by adc-dajones** [comment]
Correction - the Verisign certs do appear to be 2048-bit. But the signature algorithm appears to be SHA1 which Chrome is complaining about. Is that the issue?

The final host cert attempting to verified is www.mylandhome.com.

**Comment by Lukasa** [comment]
Please search the issue tracker: you'd have found the discussion here at #26.
