### ISSUE TITLE
Can't read https://export.arxiv.org due to CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by impredicative** [certifi/python-certifi#109]
I used to be able to read https://export.arxiv.org/ using `requests` but I can't read it anymore. Why?

```
$ python
Python 3.8.0 (default, Nov 23 2019, 05:49:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import certifi, requests

>>> certifi.__version__, requests.__version__
('2019.11.28', '2.22.0')

>>> requests.get('https://google.com')
<Response [200]>

>>> requests.get('https://export.arxiv.org/')
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 665, in urlopen
    httplib_response = self._make_request(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 376, in _make_request
    self._validate_conn(conn)
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 994, in _validate_conn
    conn.connect()
  File "/usr/local/lib/python3.8/site-packages/urllib3/connection.py", line 386, in connect
    self.sock = ssl_wrap_socket(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/ssl_.py", line 370, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/usr/local/lib/python3.8/ssl.py", line 500, in wrap_socket
    return self.sslsocket_class._create(
  File "/usr/local/lib/python3.8/ssl.py", line 1040, in _create
    self.do_handshake()
  File "/usr/local/lib/python3.8/ssl.py", line 1309, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLCertVerificationError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 439, in send
    resp = conn.urlopen(
  File "/usr/local/lib/python3.8/site-packages/urllib3/connectionpool.py", line 719, in urlopen
    retries = retries.increment(
  File "/usr/local/lib/python3.8/site-packages/urllib3/util/retry.py", line 436, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='export.arxiv.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 75, in get
    return request('get', url, params=params, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/api.py", line 60, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 533, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/sessions.py", line 646, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='export.arxiv.org', port=443): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: unable to get local issuer certificate (_ssl.c:1108)')))
```

**Comment by alex** [comment]
Was this working with certifi 2019.09.11? 2019.11.28 simply added a new root, so it's difficult for me to see how it could have caused this https://github.com/certifi/python-certifi/commit/21abb9b9bbf4c0cfecf652fadafee3eb9615d553

**Comment by alex** [comment]
Also, what version of OpenSSL is your python linked against (`import ssl; print(ssl.ssl.OPENSSL_VERSION)`)

**Comment by impredicative** [comment]
Info about `ssl`:
```
$ python
Python 3.8.0 (default, Nov 23 2019, 05:49:00) 
[GCC 8.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import ssl
>>> ssl.ssl.OPENSSL_VERSION
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'ssl' has no attribute 'ssl'
>>> ssl.OPENSSL_VERSION
'OpenSSL 1.1.1d  10 Sep 2019'
```

`export.arxiv.org` got a new certificate on Nov 25 2019 and actually that's when the problem started. I don't think it has to do with the latest version of `certifi`. I just don't know what to do about it. Thanks.

**Comment by JosephHobbs** [comment]
Have you tried to make this connection recently?  I just tested and it's working without issue.  I'm wondering if they had an issue with the certificate itself (on export.arxiv.org) and have since corrected it...
